############################## 项目启动信息配置 开始  ##############################
server:
  port: 8080
  tomcat:
    port-header: HEAD,PUT,DELETE,OPTIONS,TRACE,COPY,SEARCH,PROPFIND
    min-spare-threads: 20
    max-threads: 500
  connection-timeout: 10000
  #servlet:
    # context-path: /mmd
############################## 项目启动信息配置 结束  ##############################
############################## 数据库配置 开始 #####################################
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #在这里边明确指定serverTimezone其实是为了使MySQL JDBC驱动程序的5.1.33版本与UTC时区配合使用，必须在连接字符串中明确指定serverTimezone。
    url: jdbc:mysql://localhost:3306/mikuMaster?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC


    username: root
    password:
############################## 数据库配置 结束 #####################################
############################## 修改thymelea模板 开始################################
  thymeleaf:
    prefix: classpath:/web/
    suffix: html
    encoding: UTF-8
    content-type: text/html
    cache: false
############################## 修改thymelea模板 结束################################
############################## 修改静态资源配置 开始##################################
  mvc: 
    static-path-pattern: /static/**         # 静态资源路径
############################## 修改静态资源配置 开始##################################
############################## Mybatis 配置开始 ####################################
mybatis-plus:
  mapper-locations: classpath*:com/**/mapping/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.bone.miku.**.model,com.xxxx.**.model
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: false
      #数据库大写下划线转换
      #capital-mode: false
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  logging:
    level: warn
############################## Mybatis 配置 结束 ####################################